#!/usr/bin/env python
# 
# nom - a program that doesn't do much yet
#

import os
import commands
import dispatcher
from store import MockStore
from index import Index

class Config:
	nomDir = ".nom" #FIXME should be $HOME/nom
	storeDir = os.path.join(nomDir, "store")

	def __init__(self):
			# XXX both of these constructors are responsible for creating 
			# files and directories if they don't exists, 
			# might want to rethink this
			store = MockStore(self)
			index = Index(self)

# in the future this might load a config
# but for now, just use the constants
cfg = Config()
dispatcher.run(cfg)
